name: Qt Linux 完整打包(仅适配Ubuntu22)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-linux:
    # 你要的 22.04
    runs-on: ubuntu-22.04

    steps:
      - name: 拉取代码
        uses: actions/checkout@v5

      - name: 安装依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libgl1-mesa-dev libxkbcommon-x11-0 libxcb-*

      - name: 安装 Qt 环境
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.6.2'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          modules: 'qtwebsockets'
          setup-python: false

      - name: 编译项目
        run: |
          mkdir build && cd build
          qmake ../qt_im_project_linux.pro
          make -j4

      - name: 复制图片资源
        run: |
          cp -r btnimage build/

      - name: 打包完整依赖
        run: |
          cd build
          rm -f $QT_ROOT_DIR/plugins/sqldrivers/libqsqlmimer.so
          echo "[Desktop Entry]
          Type=Application
          Name=Qt_IM_Project
          Exec=qt_im_project_linux
          Icon=qt
          Categories=Utility;Application;" > qt_im_project_linux.desktop
          touch qt.png
          wget -c https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          chmod +x linuxdeployqt-continuous-x86_64.AppImage
          ./linuxdeployqt-continuous-x86_64.AppImage qt_im_project_linux -appimage

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: Qt_IM_Project_Linux_Full
          path: build/*.AppImage